name: Check links
on:
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: https://www.digitraffic.fi
          concurrency: 5
          recurse: true
          markdown: true
          linksToSkip: "https://jsfiddle.net, https:\/\/www.digitraffic.fi\/tiedotteet\/(2017|2018|2019|2020|2021|2022)\/, https:\/\/www.digitraffic.fi\/en\/news\/(2017|2018|2019|2020|2021|2022)\/"
