name: Check links
on:
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Link checking
        id: link_check
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: https://www.digitraffic.fi
          concurrency: 5
          recurse: true
          markdown: true
          linksToSkip: "https://jsfiddle.net, ^https://www.digitraffic.fi/tiedotteet/(2017|2018|2019|2020|2021|2022)/, ^https://www.digitraffic.fi/en/news/(2017|2018|2019|2020|2021|2022)/"
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo, job
          text: "www.digitraffic.fi link check failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}